apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: smanzy
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: smanzy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ghcr.io/vozigo/smanzary-backend:1.11.2
        imagePullPolicy: Always
        command: ["./server", "-migrate"]
        ports:
        - containerPort: 8080
        env:
        - name: DB_DSN
          valueFrom:
            configMapKeyRef:
              name: smanzy-config
              key: DB_DSN
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: smanzy-secrets
              key: JWT_SECRET
        - name: SERVER_PORT
          valueFrom:
            configMapKeyRef:
              name: smanzy-config
              key: SERVER_PORT
        - name: UPLOAD_DIR
          valueFrom:
            configMapKeyRef:
              name: smanzy-config
              key: UPLOAD_DIR
        - name: MEDIA_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: smanzy-config
              key: MEDIA_BASE_URL
        - name: GIN_MODE
          valueFrom:
            configMapKeyRef:
              name: smanzy-config
              key: GIN_MODE
        - name: YOUTUBE_API_KEY
          valueFrom:
            secretKeyRef:
              name: smanzy-secrets
              key: YOUTUBE_API_KEY
        - name: YOUTUBE_CHANNEL_ID
          valueFrom:
            secretKeyRef:
              name: smanzy-secrets
              key: YOUTUBE_CHANNEL_ID
        volumeMounts:
        - name: uploads-storage
          mountPath: /app/uploads
      volumes:
      - name: uploads-storage
        persistentVolumeClaim:
          claimName: uploads-pvc