name: Build All Services

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  # We use the organization name (lowercase) as the base
  ORG_NAME: vozigo

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # --- SERVICE 1: FRONTEND ---
      - name: Build and push Frontend
        uses: docker/build-push-action@v4
        with:
          context: ./smanzy_react_spa
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.ORG_NAME }}/smanzary-frontend:latest

      # --- SERVICE 2: BACKEND ---
      - name: Build and push Backend
        uses: docker/build-push-action@v4
        with:
          context: ./smanzy_backend
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.ORG_NAME }}/smanzary-backend:latest

      # --- SERVICE 3: THUMBNAILER ---
      - name: Build and push Thumbnailer
        uses: docker/build-push-action@v4
        with:
          context: ./smanzy_thumbgen
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.ORG_NAME }}/smanzary-thumbnailer:latest

  # JOB 2: DEPLOY TO SERVER (The New Part)
  # to be uncoment if you want to deploy to server
  # deploy:
  #   needs: build-and-push  # Wait for build to finish
  #   runs-on: ubuntu-latest
    
  #   steps:
  #     - name: Deploy via SSH
  #       uses: appleboy/ssh-action@v0.1.10
  #       with:
  #         host: ${{ secrets.SERVER_HOST }}
  #         username: ${{ secrets.SERVER_USER }}
  #         key: ${{ secrets.SSH_PRIVATE_KEY }}
  #         script: |
  #           # 1. Force Kubernetes to restart pods
  #           # Since we are using ':latest', we just need a restart to pull the new image.
            
  #           kubectl rollout restart deployment/backend-deployment -n smanzy
  #           kubectl rollout restart deployment/frontend-deployment -n smanzy
  #           kubectl rollout restart deployment/thumbnailer-deployment -n smanzy
            
  #           # 2. Check status
  #           kubectl get pods -n smanzy