name: Composer Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: "conta.sman.cloud"
          username: "ristepan"
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          debug: true
          script: |
            echo "Testing SSH connection"

        # with:
        #   host: ${{ secrets.SERVER_HOST }}
        #   username: ${{ secrets.SERVER_USER }}
        #   key: ${{ secrets.SSH_PRIVATE_KEY }}
        #   script: |
        #     set -e
        #     cd /home/ristepan/smanzari_site
        #     git pull origin main
        #     docker compose -f docker-compose.prod.yml up -d --build
        #     # docker system prune -f # disabled for now
